name: Staging Release(Part2)

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "apps/part2/**"

env:
  ACR_NAME: acrcontainerappopening

jobs:
  push_image:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: "apps/part2"

    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build & Push Image
      run: |
        az acr login -n ${{ env.ACR_NAME }} -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
        mvn compile test com.google.cloud.tools:jib-maven-plugin:3.2.1:build \
          -Djib.from.image=eclipse-temurin:17.0.4_8-jre-alpine \
          -Djib.to.image=${{ env.ACR_NAME }}.azurecr.io/todolist:${project.version} \
          -Djib.to.tags=v1.0.0-tem_17.04_8-jre-alpine_GITHUB_SHA,latest \
          -Djib.to.auth.username=${{ secrets.ACR_USERNAME }} \
          -Djib.to.auth.password=${{ secrets.ACR_PASSWORD }} \
          -Djib.container.entrypoint=sh,webapp_startup.sh \
          -Djib.container.ports=8080,2222 \
          -Djib.container.environment=JDK_JAVA_OPTIONS="-Xmx512m -XX:StartFlightRecording"